
\newpage

# Introduction {-}

`r ifelse(book_format == "html" & with_watermark, "<div class='watermark'>DRAFT</div>", "")`

<txt-green>Welcome to the part 2 of the second lesson</txt-green> of the National Forest Inventory eLearning Practice Simulation.

In Lesson 1, we had a quick overview of `Louland` and preliminary data gathered to help us prepare a sampling design and implement an NFI.

In the first part of this lesson 2, we have estimated that measuring around 300 plots, which is our cost constraint, would give us a precision on aboveground biomass of around 10%. We have then tested two "simple" sampling designs and selected the systematic sampling on a 4 x 4 km grid as our optimal design.


::::::{.infobox data-latex=""}

Small reminder, this interactive module is designed to complement the National Forest Inventory eLearning Modules with practical hands-on exercises on a fictional island that just emerged in the middle of the Atlantic Ocean: `Louland`. The lesson 2 focuses on several sampling methods that we called "simple sampling" as they are based on the <txt-green>simple random sampling statistics</txt-green>. 

As we have seen in the NFI eLearning Modules, NFI are multi-purposes but the sampling design requires that we focus on one main variable of interest. In this lesson 2, <txt-green>the main variable of interest is the forest mean aboveground biomass</txt-green> of `r newland_name`. For this lesson2, we will limit ourselves to random and systematic sampling and we will obtain aboveground biomass estimates for each forest type through post-stratification.

::::::

We will now start Lesson 2 part 2. The sampling design was handed over to the implementation crew. They developed a field manual and field forms and three crews measured the plots on our 4 x 4 km sampling grid. The data has been digitized and transferred back to you. In this lesson we will develop carbon stock estimates for `r newland_name`'s forests. The objectives of the part 2 are:

- Screen through the variables measured in the field.
- Perform a small data cleaning to detect and correct potential measurement or data entry errors.
- Add ancillary data to complement field measurement and estimate tree aboveground biomass.
- Propagate tree aboveground biomass to plot and forest type estimates.
- Calculate the uncertainty related to the sampling size.


::::::{.infobox data-latex=""}

This Lesson is voluntary oversimplified to illustrate key concepts related to NFI data analysis. It is based on real tree measurements but the data has been curated to keep the lesson easy and user-friendly. With a real National Forest Inventory the data cleaning process might take days to weeks to scrutinize the many collected variables. Model development might be added to detect potential outliers in tree height and diameters and will be covered in a more advanced lesson.

::::::

<txt-green>Let's get started!</txt-green>



